[package]
name = "library_dev"
version = "0.1"
timeout = 20000
path = "src"

[dependencies]
super = {git = "https://github.com/leanprover/super.git", rev = "1448ed15556583231994897ea9a549fd42fd9c0d"}
